# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Moise K. Kameni
title: DevOps and Cloud Evangelist
email: moise@kamgoue.me
website: kamgoue.me

# Social links
# twitter_username: facespics
github_username:  mkameni
# dribbble_username: jekyll
facebook_username: moise.kam
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: moisekameni
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Moise passionate of technologies, development and operation (system administration) in particular. The cloud is my playground. I worked in multiple companies which allowed me to touch several projects, several technologies and gain huge experience in the field of DevOps and Cloud. Today I support teams and companies to do DevOps transformation and migrate legacy infrastructures in the Cloud with good practices.

  I am most skilled in: <mark>AWS</mark>, <mark>GCP</mark>, <mark>Azure</mark>, <mark>Openstack</mark>, <mark>Baremetal</mark> and <mark>Eating Pizza</mark>

# Projects Section
projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in IT some of my other interests and hobbies are:
   - Watch and play football
   - Travel
   - Unboarding immigrant newcomer in Canada
  #  - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true/false
